<?php
/**
 * Tpl_EventsManager extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Tpl
 * @package        Tpl_EventsManager
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event view widget template
 *
 * @category    Tpl
 * @package     Tpl_EventsManager
 * @author      TPL
 */
?>
<?php
$_events = Mage::getModel('tpl_eventsmanager/event')->getAllEvents();
$time = microtime();
$time = str_replace(' ', '', $time);
?>
<div class="banner-slider-tile" id="events-banner-slider_<?php echo $time; ?>" >    
    <?php
    $flag = 0;
    foreach ($_events as $_event) :
        ?>
        <?php
        $curdate = strtotime(date('Y-m-d 00:00:00'));
        $end_date = strtotime($_event->getEndDate());
        ?>
        <?php if (($curdate <= $end_date) && (!empty($_event->getBanner()))): ?>

            <a href="<?php echo $_event->getEventUrl() ?>">
                <div alt="<?php echo $_event->getEventName(); ?>" title="<?php echo $_event->getEventName(); ?>" style="display:<?php
                if ($flag == 0) {
                    echo 'block';
                } else {
                    echo 'none';
                }
                ?> ; background: url(<?php echo Mage::helper('tpl_eventsmanager/event_image')->init($_event, 'banner'); ?>) no-repeat center center; padding-bottom:20%;  -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover;  background-size: cover;" class="event-thumbnail" >
                </div>
            </a>
            <?php
            $flag = 1;
        endif;
        ?>

    <?php endforeach; ?>
</div>  

<script>
    window.onload = shuffle_banners();

    function shuffle_banners() {
        var banner_div = document.getElementById('events-banner-slider_<?php echo $time; ?>');
        var all_images = banner_div.getElementsByTagName("div");

        var len = all_images.length;
        console.log(all_images);
        var index = 0;
        setInterval(function () {
            if (index != 0)
            {
                all_images[index - 1].style.display = "none";
            }
            if (index > (len - 1))
            {
                index = 0;
            }
            all_images[index].style.display = "block";

            index++;
        }, 2000);

    }
</script>

<style>
    .banner-slider-tile {
        margin-top: 20px;
        margin-bottom: 10px;
        /*        padding: 10px;*/
        display: block;
        background: #F3F3F3;
        border: solid;
        border-width: 1px;
        border-color: #D4D4D4;
        width: 100%;

        overflow: hidden;
    }
</style>
