<?php
/**
 * Tpl_EventsManager extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Tpl
 * @package        Tpl_EventsManager
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event link widget template
 *
 * @category    Tpl
 * @package     Tpl_EventsManager
 * @author      TPL
 */
?>

<?php // widget displays upcomming and not expired events   ?>
<style>
    .upcomming-event-list{
        margin-top: 10px;
        max-height: 300px;
        overflow-x: scroll;
        overflow-x: auto;
    }
    .upcomming-event-thumbnail {
        float: left;
        width: 100%;
        margin-right: 6px;
        margin-bottom: 2px;

    }
    .upcomming-event-list img{
        max-width: 85px;
        min-width: 5px;
/*        padding: 5px;*/
        margin: 5px; 
    }
    .upcomming-event-list-item{
        width: 100%;
        padding-bottom: 12px;
        overflow: hidden;
        padding-left: 5px;
padding-right: 2px;
    }

</style>

<div class="block">
    <div class="block-title">
        <strong><span>&nbsp; Upcoming Events</span></strong>
    </div>
    <div class=" block-content " style="padding: 1px;">
        <?php $_events = $this->getEvents(); ?>
        <?php if ($_events->getSize() > 0) : ?>
            <div class="upcomming-event-list">            
                <?php $curdate = strtotime(date('Y-m-d 00:00:00')); ?>
                <?php
                foreach ($_events as $_event) :
                    $end_date = strtotime($_event->getEndDate());
                    if (($curdate <= $end_date)) {
                        ?>

                        <div class="upcomming-event-list-item">
                            <div style="width:60px;">
                            <div class="upcomming-event-thumbnail">
                                <a href="<?php echo $_event->getEventUrl() ?>">
                                    <?php if ($_event->getThumbnail() == "") { ?>
                                    
                                        <div  class="event-thumbnail img-responsive" style="background: url(<?php echo Mage::getBaseUrl('skin') . "frontend/base/default/images/tpl_eventsmanager/no-image-available.png"; ?>) no-repeat center center; padding-bottom:100%;  -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover;  background-size: cover;" alt="<?php echo $this->escapeHtml($_event->getEventName()); ?>" >
                                        </div>
                                    
                                    <?php } else { ?>
                                        <div  title="<?php echo $_event->getEventName(); ?>" class="event-thumbnail img-responsive" style="background: url(<?php echo Mage::helper('tpl_eventsmanager/event_image')->init($_event, 'thumbnail');?>) no-repeat center center; padding-bottom:100%;  -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover;  background-size: cover;" alt="<?php echo $this->escapeHtml($_event->getEventName()); ?>" >
                                        </div>
                                    <?php } ?>
                                </a>
                            </div>
                            </div>    
                            <a  style="text-decoration: none;"href="<?php echo $_event->getEventUrl() ?>">
                                <div style="height:15px; width: 15px; border-radius: 2px; background: <?php echo $_event->getColor(); ?>;float:right; margin:2px;" title="Event Color Code"></div>
                                <strong><?php echo $_event->getEventName(); ?></strong>
                            </a>


                            <p>
                                <?php echo strip_tags(substr($_event->getDescription(), 0, 50)); ?>...
                            </p>

                        </div>
                        <?php
                    }
                endforeach;
                ?>

            </div>               
        <?php else : ?>
            <?php echo Mage::helper('tpl_eventsmanager')->__('There are no events at this moment'); ?>
        <?php endif; ?>
    </div>
</div>    









