<?php
/**
 * Tpl_EventsManager extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Tpl
 * @package        Tpl_EventsManager
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event link widget template
 *
 * @category    Tpl
 * @package     Tpl_EventsManager
 * @author      TPL
 */
?>
<?php //$_event = $this->getCurrentEvent();
?>
<?php //if ($_event) :
?>
<!--    <div class="event-widget-link">
        <a href="<?php //echo $_event->getEventUrl()      ?>"><?php //echo $_event->getEventName()      ?></a>
    </div>-->
<?php // widget displays upcomming and not expired events   ?>
<div class="block">
    <div class="block-title">
        <strong><span>&nbsp; Upcoming Events</span></strong>
    </div>
    <div class=" block-content col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php $_events = $this->getEvents(); ?>
        <?php if ($_events->getSize() > 0) : ?>
            <!--            <div class="widget-event-list-container">-->
            <?php $curdate = strtotime(date('Y-m-d 00:00:00')); ?>
            <?php
            foreach ($_events as $_event) :
                $end_date = strtotime($_event->getEndDate());
                if (($curdate <= $end_date)) {
                    ?>
            <div class="widget-event-list-item">
                    <div class=" col-xs-4 col-sm-4 col-md-4 col-lg-4">

                        <a href="<?php echo $_event->getEventUrl() ?>">
                            <img title="<?php echo $_event->getEventName(); ?>" class="img-responsive" src="<?php echo Mage::helper('tpl_eventsmanager/event_image')->init($_event, 'thumbnail')->resize(150, 150); ?>" alt="<?php echo $this->escapeHtml($_event->getEventName()); ?>" />
                    </div>

                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 widget-event-list-text">
                         <div style="height:15px; width: 15px; background: <?php echo $_event->getColor(); ?>;float:right;" title="Event Color Code"></div>
                        <strong><?php echo $_event->getEventName(); ?></strong></a>
                       
                        <div class="widget-event-list-event-short-desc"><p>
                                <?php echo strip_tags(substr($_event->getDescription(), 0, 50)); ?>...
                            </p>
                        </div>
                    </div>
            </div>
                    <?php
                }
            endforeach;
            ?>
            <!--        </div>-->

        <?php else : ?>
            <?php echo Mage::helper('tpl_eventsmanager')->__('There are no events at this moment'); ?>
        <?php endif; ?>
    </div>
</div>    
<style>
    .widget-event-list-container{
        margin-top: 10px;
        padding: 10px;

        height: 300px;
        overflow-x: scroll;
        overflow-x: auto;
    }
    .widget-event-list-item{
       
        padding-bottom: 12px;
       
        overflow: hidden;
    }
    .event-thumbnail{
        padding-left: 0px;
        /*        position: absolute;*/
    }
    .widget-event-list-event-type{
        float: right;

        right: 0;
        /* margin-top: -24px; */
        position: relative;
    }
    .widget-event-list-text{

        /*        margin-left: 65px;*/
        text-overflow: ellipsis;
        padding-left: 0px;

    }
    @media (max-width: 900px) {

        .widget-event-list-event-type {

            bottom: 0;
        }
    }


    @media (max-width: 400px) {
        .widget-event-list-event-type{
            display: none;
        }
    }


    .widget-event-list-event-short-desc{

        overflow: hidden;
        width: 80%;
        height: 39px;
        /*    white-space: nowrap;*/
        text-align: justify;
    }
</style>









