<?php
/**
 * Tpl_EventsManager extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Tpl
 * @package        Tpl_EventsManager
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event comments form template
 *
 * @category    Tpl
 * @package     Tpl_EventsManager
 * @author      TPL
 */
?>
<style>
/*    .comments-tile{
        border: 1px solid rgb(247, 247, 247);
    }*/


    input[type="text"] {
        width: 100%;
    }
</style>
<div class="cms-page-view row"  itemscope itemtype="http://schema.org/Event">
<?php
$data = $this->getCommentData();
if ($this->getEvent()) {
    ?>
    <br/>
    <div class="comments-tile col-xs-12 col-sm-12 col-md-12 col-lg-12 form-add  " style=" padding: 25px;margin-top: 10px;">
        <h2><?php echo $this->__('Your Comment') ?></h2>
        <?php if ($this->getAllowWriteCommentFlag()): ?>
            <form action="<?php echo $this->getAction() ?>" method="post" id="comment-form">
                <fieldset >
                    <div class="form-list">
                        <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                            <div>
                                <input type="hidden" name="name" id="name_field" class="input-text required-entry" value="<?php
                                if ($this->escapeHtml($data->getName()) == "") {
                                    echo 'Anonymous';
                                } else {
                                    echo $this->escapeHtml($data->getName());
                                }
                                ?>" />
                            </div>
                            <div>
                                <input type="hidden" name="email" id="email_field" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($data->getEmail()) ?>" />
                            </div>
                        <?php else: ?>

                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                                <label for="nickname_field" class="required col-xs-12"><em>*</em><?php echo $this->__('Nickname') ?></label>
                                <div class="col-xs-12 col-lg-7">
                                    <input type="text" name="name" id="name_field" class="form-control required-entry" value="<?php echo 'Anonymous'; ?>" required/>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                                <label for="email_field" class="required col-xs-12"><em>*</em><?php echo $this->__('E-mail') ?></label>
                                <div class="col-xs-12 col-lg-7">
                                    <input type="text" name="email" id="email_field" class="required-entry form-control validate-email" value="<?php echo $this->escapeHtml($data->getEmail()) ?>" required/>
                                </div>
                            </div>

                        <?php endif; ?>

                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                            <label for="title_field" class="required col-xs-12"><em>*</em><?php echo $this->__('Comment title') ?></label>
                            <div class="col-xs-12 col-lg-7">
                                <input type="text" name="title" id="title_field" class=" required-entry form-control" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" required/>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                            <label for="review_field" class="required col-xs-12"><em>*</em><?php echo $this->__('Comment') ?></label>
                            <div class="col-xs-12 col-lg-7">
                                <textarea name="comment" id="comment_field"  class="required-entry" required><?php echo $this->escapeHtml($data->getComment()) ?></textarea>
                            </div>
                        </div>

                    </div>
                    <?php if (Mage::getSingleton('customer/session')->isLoggedIn() && Mage::getStoreConfig('tpl_eventsmanager/customsettings/anonymous_comments', Mage::app()->getStore())): ?>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">  
                            <div class="input-box col-xs-12">
                                <input type="checkbox" name="anonymous" id="anonymous_field"  class="required-entry" onchange="anonymous_comment(event)" >&nbsp; Comment as Anonymous</input>
                            </div>
                        </div>
                    <?php endif; ?>

                </fieldset>
                <div class="buttons-set">
                    <button type="submit" title="<?php echo $this->__('Submit Comment') ?>" class="button"><span><span><?php echo $this->__('Submit Comment') ?></span></span></button>
                </div>
            </form>

            <script type="text/javascript">var commentForm = new VarienForm('comment-form');</script>
        <?php else: ?>
            <p class="review-nologged" id="comment-form">
                <?php echo $this->__('Only registered users can write comments. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
            </p>
        <?php endif ?>
    
    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <script>
            var original_name;
            var original_email;
            function anonymous_comment(event) {
                var checkbox = event.target;
                if (checkbox.checked) {
                    var name = document.getElementById('name_field');
                    var email = document.getElementById('email_field');
                    original_name = name.value;
                    original_email = email.value;
                    name.value = 'Anonymous';
                    email.value = 'Anonymous';
                } else {
                    var name = document.getElementById('name_field');
                    var email = document.getElementById('email_field');
                    name.value = original_name;
                    email.value = original_email;
                }
            }
        </script>
    <?php endif; ?>    
  </div>
    <?php
}?>
</div>