<?php
/**
 * Tpl_EventsManager extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Tpl
 * @package        Tpl_EventsManager
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event comments list template
 *
 * @category    Tpl
 * @package     Tpl_EventsManager
 * @author      TPL
 */
?>
<?php
$_event = Mage::helper('tpl_eventsmanager/event')->validateCurrentEvent();
if ($_event) {
    ?>
    <?php if ($_event->getAllowComments()) : ?>
        <?php $_comments = $this->getComments(); ?>
        <?php if (count($_comments)) : ?>
            <div class="box-collateral box-reviews col-xs-12 col-sm-12 col-md-12 col-lg-12" id="event-reviews">
                <h2><?php echo $this->__('Comments for: %s', $_event->getEventName()) ?></h2>
                    <?php echo $this->getPagerHtml() ?>
                <dl>
            <?php foreach ($_comments as $_comment): ?>
                        <dt style=" margin-top: 30px;">
                            <div class="author"><?php echo $this->__('On %s %s wrote:', $this->formatDate($_comment->getCreatedAt(), 'long'), $this->escapeHtml($_comment->getName())) ?></div>
                            <strong><?php echo $this->escapeHtml($_comment->getTitle()) ?></strong>
                        </dt>
                        <dd style="margin-bottom: 20px;">
                        <?php echo nl2br($this->escapeHtml($_comment->getComment())) ?>
                        </dd>
                <?php endforeach; ?>
                </dl>
            <?php echo $this->getPagerHtml() ?>
            </div>
        <?php endif; ?>
        <?php echo $this->getChildHtml('comment_form') ?>
    <?php endif;
} ?>
