<?php
/**
 * Tpl_EventsManager extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Tpl
 * @package        Tpl_EventsManager
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event view template
 *
 * @category    Tpl
 * @package     Tpl_EventsManager
 * @author      TPL
 */
?>
<?php
$_notification_events = $this->getEvents();
if (count($_notification_events) && count(Mage::getSingleton('core/session')->getData('closedevents')) != count($_notification_events)):

    foreach ($_notification_events as $event) {
        ?>

        <?php
        $temp = array();
        if (!empty(Mage::getSingleton('core/session')->getData('closedevents'))) {
            $temp = Mage::getSingleton('core/session')->getData('closedevents');
        }
        // not in
        if (!in_array($event->getEntityId(), $temp)) {
            ?>
            <ul class="messages">
                <li class="notice-msg" >
                    <ul>
                        <li style="overflow: auto;">
                            <a style="text-decoration: none;" href="<?php echo $event->getEventUrl() ?>">
                            <span style=" display: inline-block;"><?php
            echo $event->getEventName();
            ?></span></a>
                            <span class="actions" style="float: right;  display: inline-block;  top: 0px; position: inherit;" ><a  id="notification-button" href="<?php echo $event->getEventUrl() ?>"><button style="padding: 1px 15px;"  class="button"><span><span>View Detail</span></span></button></a>
                                &nbsp; <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>index.php/tpl_eventsmanager/event/closenotification?eventid=<?php echo $event->getEntityId(); ?>"><img style="float: right; margin-top: 3px;" height="15" width="15"   src="<?php echo Mage::getBaseUrl('skin') . 'frontend/base/default/images/tpl_eventsmanager/close-button.svg'; ?> " /></a>
                            </span>
                        </li>
                    <?php } ?>

                    <?php ?>
                </ul>
            </li>
        </ul>
    <?php }

endif;
?>
<!--<style>
    @media only screen and (max-width: 1000px) { 
        #notification-button { 
            display: none; 
        } 
    }
</style>-->