<?php
/**
 * Tpl_EventsManager extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Tpl
 * @package        Tpl_EventsManager
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event list template on product page
 *
 * @category    Tpl
 * @package     Tpl_EventsManager
 * @author      TPL
 */
?>
<?php $events = $this->getEventCollection();?>
<?php if ($events && $events->count() > 0) :?>
<div class="box-collateral box-events box-up-sell">
    <?php foreach ($events as $_event) : ?>
        <div class="item">
            <a href="<?php echo $_event->getEventUrl()?>">
                <?php echo $_event->getEventName();?>
            </a><br />
        </div>
    <?php endforeach; ?>
</div>
<?php endif;?>
